version: '3.8'
services:
  backend:
    build: ./backend
    networks:
      - network
    container_name: jsbalance-backend
    ports:
      - "3000:81"
  frontend:
    build: ./frontend
    networks:
      - network
    container_name: jsbalance-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
networks:
  network:
    driver: bridge