version: '3.8'
services:
  backend:
    build: ./backend
    networks:
      - network
    container_name: jsbalance-backend
    # port only temporarily open
    ports:
      - "81:81"
  # not finished yet
  # frontend:
  #   build: ./frontend
  #   networks:
  #     - network
  #   container_name: jsbalance-frontend
  #   ports:
  #     - "80:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - "PRODUCTION=TRUE"
networks:
  network:
    driver: bridge